### ISSUE TITLE
Using Strawbery Perl for both 5.34 and 5.38

### ISSUE THREAD

**Issue by ferki** [shogo82148/actions-setup-perl#2417]
Thanks again for your work on #2151 and #2349 to include both the 5.34 and 5.38 versions of Strawberry Perl!

While using this action, I noticed the following:

- when using current latest v1.36.0, it can not download Strawberry Perl 5.34 (specifically 5.34.3.1)
- when using the latest commit of this action, it can’t download Strawberry Perl 5.38 (specifically 5.38.4.1)

Could you advise how to use both Perl versions in a given workflow, please?

Does this repo or the shogo82148/strawberry-perl-releases repo need a new release first?

How I may help and contribute the necessary changes?

**Comment by shogo82148** [comment]
I've released https://github.com/shogo82148/actions-setup-perl/releases/tag/v1.37.0 now.
please try it.

**Comment by ferki** [comment]
Thank you for the release! It works for 5.34.3.1, though still fails for 5.38 with the following:

>   Downloading https://github.com/shogo82148/strawberry-perl-releases/releases/download/5.38.4.1/strawberry-perl-5.38.4.1-64bit-portable.zip
Error: Error: Failed to download version [object Object]: Error: Unexpected HTTP response: 404
